name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - run: npm install markdown-styles
    - uses: actions/checkout@master
    - run: npx generate-md --layout github --input ./content --output ./output
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.OVH_HOST }}
        username: github
        password: ${{ secrets.OVH_GITHUB_PASSWORD }}
        source: "output/*"
        target: "/var/www/val3k.me"